spring:
  application:
    name: aegisIdentity
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    discovery:
      enabled: true
server:
  port: 0
  servlet:
    context-path: /

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
jwt:
  secret: 22b0ef20d7ec3777ea19cf5e8f17ca946e274b0f3d6202c50299efbd511965bb
  expiration-ms: 3600000
